using Newtonsoft.Json;
using System;

namespace strngr_dngr.Model.Response.WhitePages
{
    [Serializable]
    public class EmailChecks
    {
        [JsonProperty(PropertyName = "error")]
        public string Error { get; set; }

        [JsonProperty(PropertyName = "warnings")]
        public string[] Warnings { get; set; }

        [JsonProperty(PropertyName = "is_valid")]
        public bool? IsValid { get; set; }

        [JsonProperty(PropertyName = "is_autogenerated")]
        public bool? IsAutogenerated { get; set; }

        [JsonProperty(PropertyName = "is_disposable")]
        public bool? IsDisposable { get; set; }

        [JsonProperty(PropertyName = "email_first_seen_days")]
        public long? EmailFirstSeenDays { get; set; }

        [JsonProperty(PropertyName = "email_domain_creation_days")]
        public long? EmailDomainCreationDays { get; set; }

        [JsonProperty(PropertyName = "match_to_name")]
        public string MatchToName { get; set; }

        [JsonProperty(PropertyName = "match_to_address")]
        public string MatchToAddress { get; set; }

        [JsonProperty(PropertyName = "registered_owner")]
        public Subscriber RegisteredOwner { get; set; }
    }
}
